# Generated by Django 3.2.8 on 2021-10-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20211007_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='points',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
