# Generated by Django 3.2.8 on 2021-10-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20211007_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='timestamp',
            field=models.CharField(max_length=100),
        ),
    ]
