# Generated by Django 3.2.8 on 2021-10-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transactions_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='payer',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
