# Generated by Django 3.2.8 on 2021-10-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_transactions_payer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='payer',
            field=models.CharField(max_length=100),
        ),
    ]
